default_language_version:
  python: python3.11

#default_stages: [commit, push]
files: "^(docker|aeon\/dj_pipeline)\/.*$"
repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: no-commit-to-branch

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args:
          - "--config"
          - "./pyproject.toml"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          - "--settings-file"
          - "./pyproject.toml"
  
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
        - id: flake8
          entry: pflake8
          additional_dependencies: [pyproject-flake8]
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        args:
          - "--config-file"
          - "./pyproject.toml"

  # Bandit and Pytest are expensive, so we show their set-up but leave them commented out.
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #     - id: bandit
  #       args:
  #         - "--configfile"
  #         - "./pyproject.toml"
  #         - "--recursive"
  #         - "-ll"
  #       additional_dependencies:
  #         - "bandit[toml]"

  # - repo: local
  #   hooks:
  #     - id: pytest-py
  #       name: pytest-py
  #       entry: pytest
  #       language: system
  #       pass_filenames: false
  #       args:
  #         - "-v"
  #         - "-n"
  #         - "auto"
