name: Empty Default Action
on:
  push:
    branches: [main]

jobs:
  Empty-Default-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by ${{ github.repository_owner }} from a ${{ github.event_name }} event."
      # - name: Show GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
