# Builds the aeon environment, flakes via flake8, tests via pytest, and
# test coverage report via pytest-cov and codecov.

name: build_env_run_tests
on:
  push:
    branches: [ main, reorg, jai_dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows running manually from Github's 'Actions' tab
jobs:
  build_env_run_tests:
    name: Build env and run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0} # reset shell for each step
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: set up conda env
        uses: conda-incubator/setup-miniconda@v2  # from github marketplace
        with:
          activate-environment: aeon
          environment-file: env.yml
          use-mamba: true
          miniforge-variant: Mambaforge
      #- name: flake
        #run: python -m flake8 .
      - name: pytest
        run: python -m pytest tests/
      - name: generate test coverage report
        run: |
          python -m pytest --cov=aeon ./tests/ --cov-report=xml:./tests/test_coverage/cov_report.xml
          python -m pytest --cov=aeon ./tests/ --cov-report=html:./tests/test_coverage/cov_report_html/
      - name: upload test coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ab5c4418-b0c1-4c7e-9472-c484a8ed6906
          directory: ./tests/test_coverage/
          files: cov_report.xml
          fail_ci_if_error: true
          verbose: true
