name: Aeon Container Environment

on:
  push:
    branches: [datajoint_pipeline]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: v0.0.0a

      - name: Get current date
        id: timestamp
        run: echo "::set-output name=date::$(date -d @${{ steps.previoustag.outputs.timestamp }} +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Set docker image UID and GID defaults
        id: usergroupid
        run: |
          DJ_WORKER_UID=${{ secrets.DJ_WORKER_UID }}
          DJ_WORKER_GID=${{ secrets.DJ_WORKER_GID }}
          echo "::set-output name=uid::${DJ_WORKER_UID:-6001}"
          echo "::set-output name=gid::${DJ_WORKER_GID:-6001}"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
          buildkitd-flags: --debug

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          no-cache: true
          build-args: |
            IMAGE_CREATED=${{ steps.timestamp.outputs.date }}
            IMAGE_VERSION=${{ steps.previoustag.outputs.tag }}
            NEW_USER_UID=${{ steps.usergroupid.outputs.uid }}
            NEW_USER_GID=${{ steps.usergroupid.outputs.gid }}
          context: .
          file: docker/image/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.previoustag.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
